import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "CodeCraft: The Engineering Simulation",
  description: "Generated by Stitch",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />
      </head>
      <body suppressHydrationWarning className={`bg-[#131313] text-[#e5e2e1] selection:bg-[#00e5ff] selection:text-[#00363d] antialiased min-h-screen w-full overflow-hidden font-body-md relative`}>
        {children}
      </body>
    </html>
  );
}
